// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFlfdwMPBn6zq893oQCVdaB-vxA2s_umk',
    appId: '1:717238350591:web:8d791b6a4429e2257292ca',
    messagingSenderId: '717238350591',
    projectId: 'resqnet-25',
    authDomain: 'resqnet-25.firebaseapp.com',
    storageBucket: 'resqnet-25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIb5jpA473QRPdp19Un2OvM5amxsK-b50',
    appId: '1:717238350591:android:ef2b7f9151c920707292ca',
    messagingSenderId: '717238350591',
    projectId: 'resqnet-25',
    storageBucket: 'resqnet-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD71oFUH1Mksy5GUd02mm1pIPb2w7RVGQo',
    appId: '1:717238350591:ios:d5166d5cd0dad5a47292ca',
    messagingSenderId: '717238350591',
    projectId: 'resqnet-25',
    storageBucket: 'resqnet-25.firebasestorage.app',
    iosBundleId: 'com.example.resqnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD71oFUH1Mksy5GUd02mm1pIPb2w7RVGQo',
    appId: '1:717238350591:ios:d5166d5cd0dad5a47292ca',
    messagingSenderId: '717238350591',
    projectId: 'resqnet-25',
    storageBucket: 'resqnet-25.firebasestorage.app',
    iosBundleId: 'com.example.resqnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFlfdwMPBn6zq893oQCVdaB-vxA2s_umk',
    appId: '1:717238350591:web:15114f60c5900d6a7292ca',
    messagingSenderId: '717238350591',
    projectId: 'resqnet-25',
    authDomain: 'resqnet-25.firebaseapp.com',
    storageBucket: 'resqnet-25.firebasestorage.app',
  );
}
