// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB64LDcI7YG2ArTjXsXDWHlp00BcBOzUeE',
    appId: '1:341222348718:web:1caa58b341648c15a99a3f',
    messagingSenderId: '341222348718',
    projectId: 'smartbodahelmet',
    authDomain: 'smartbodahelmet.firebaseapp.com',
    storageBucket: 'smartbodahelmet.firebasestorage.app',
    measurementId: 'G-R0TJEQZH4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpqckP9SVY0RE93yiIzvY4e1-_t1-zY24',
    appId: '1:341222348718:android:624a84f071548cc8a99a3f',
    messagingSenderId: '341222348718',
    projectId: 'smartbodahelmet',
    storageBucket: 'smartbodahelmet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD86pAUXVDz4R1ouWtF-PMZMs46XPc4fK8',
    appId: '1:341222348718:ios:20f96d4dfa3e4d3ca99a3f',
    messagingSenderId: '341222348718',
    projectId: 'smartbodahelmet',
    storageBucket: 'smartbodahelmet.firebasestorage.app',
    iosBundleId: 'com.example.resqnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD86pAUXVDz4R1ouWtF-PMZMs46XPc4fK8',
    appId: '1:341222348718:ios:20f96d4dfa3e4d3ca99a3f',
    messagingSenderId: '341222348718',
    projectId: 'smartbodahelmet',
    storageBucket: 'smartbodahelmet.firebasestorage.app',
    iosBundleId: 'com.example.resqnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB64LDcI7YG2ArTjXsXDWHlp00BcBOzUeE',
    appId: '1:341222348718:web:e6bae70328bfef43a99a3f',
    messagingSenderId: '341222348718',
    projectId: 'smartbodahelmet',
    authDomain: 'smartbodahelmet.firebaseapp.com',
    storageBucket: 'smartbodahelmet.firebasestorage.app',
    measurementId: 'G-X02W9Y7XZN',
  );

}